name: "CI"
on:
  pull_request:
  push:
jobs:
  nix-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0
    - uses: cachix/install-nix-action@v13
      with:
        install_url:        https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210415_76980a1/install
    - run: echo "experimental-features = nix-command flakes" | sudo tee -a /etc/nix/nix.conf

    - name: Nix Flake Check
      run: nix -Lv flake check
    - name: Build Zeek Release
      run: nix -Lv build ./#zeek-release
    - name: Check Zeek Release Version
      run: nix -Lv run .#zeek-release -- -NN
    - name: Build Zeek Master
      run: nix -Lv build ./#zeek-master
    - name: Check Zeek Master Version
      run: nix -Lv run .#zeek-master -- -NN
